import { KpiDefinition, KpiTarget } from "../models/index.js";

const PLAYBOOKS_KPIS = {
  communication_shield: {
    role: "Manager",
    kpis: [
      {
        id: "ontime",
        label: "On-time at desk by 10:30",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "A late start is a lost morning sprint.",
      },
      {
        id: "conn",
        label: "Avg connections / person",
        target: 70,
        kind: "count",
        why: "Below 70, the funnel collapses by EOD.",
      },
      {
        id: "ghost",
        label: "Ghost leads cleared",
        target: 1,
        kind: "boolean",
        why: "Zero leads without a next-step task.",
      },
      {
        id: "stuck",
        label: "Stuck WhatsApp chats >24h",
        target: 0,
        kind: "count",
        why: "Silence kills trust. Move every chat.",
      },
      {
        id: "revived",
        label: "Revived leads (7-day sweep)",
        target: 20,
        kind: "count",
        why: "Yesterday's silence is today's revenue.",
      },
      {
        id: "audited",
        label: "Lead journeys audited",
        target: 30,
        kind: "count",
        why: "Movement, not chatting. Tour-bound or out.",
      },
      {
        id: "corrections",
        label: "Real-time corrections",
        target: 5,
        kind: "count",
        why: "Fix the pitch on the call, not at debrief.",
      },
      {
        id: "windows",
        label: "Comm windows sent on time",
        target: 4,
        kind: "count",
        why: "4 windows. Not 5. Not 3. Exactly 4.",
      },
      {
        id: "scored",
        label: "Every employee scored A/B/C",
        target: 1,
        kind: "boolean",
        why: "Public scoreboard or no scoreboard.",
      },
      {
        id: "c_player_1on1",
        label: "C-player 1:1s done by 7 PM",
        target: 1,
        kind: "boolean",
        why: "C-players don't go home without a plan.",
      },
    ],
    owners: ["e12"],
  },
  performance_enforcer: {
    role: "Manager",
    kpis: [
      {
        id: "booked",
        label: "Tours booked",
        target: 16,
        kind: "count",
        why: "16 to guarantee 10 done at 60% show-up.",
      },
      {
        id: "done",
        label: "Tours completed",
        target: 10,
        kind: "count",
        why: "10 is the floor. Below 10 = no revenue day.",
      },
      {
        id: "showup",
        label: "Show-up % this week",
        target: 60,
        unit: "%",
        kind: "percent",
        why: "Below 60% = pitch or confirmation broken.",
      },
      {
        id: "closings",
        label: "TCM closings (after 6 tours)",
        target: 2,
        kind: "count",
        why: "6 tours and no close = the ask was missed.",
      },
      {
        id: "noshows",
        label: "No-shows analyzed",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Every no-show has a named reason. No exceptions.",
      },
      {
        id: "pitch_fix",
        label: "Pitch corrections sent",
        target: 5,
        kind: "count",
        why: "Specific quote → specific fix → next call.",
      },
      {
        id: "tomorrow",
        label: "Tomorrow's morning tours confirmed",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Confirmed today, or it's already broken.",
      },
      {
        id: "ooo",
        label: "OOO team connected",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Silence in the morning = drift all day.",
      },
      {
        id: "calls_listened",
        label: "Live calls listened-in",
        target: 8,
        kind: "count",
        why: "Coach in the moment, not at debrief.",
      },
      {
        id: "red_zone_named",
        label: "Red-zone names published",
        target: 1,
        kind: "boolean",
        why: "If the floor doesn't see it, it isn't real.",
      },
      {
        id: "tcm_six_rule",
        label: "TCMs hitting 6-tour rule",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Below 6 = the ask was never made.",
      },
      {
        id: "evening_ranking",
        label: "Evening ranking posted",
        target: 1,
        kind: "boolean",
        why: "Public leaderboard at 6 PM. No exceptions.",
      },
    ],
    owners: ["e13"],
  },
  training_architect: {
    role: "Manager",
    kpis: [
      {
        id: "day0",
        label: "Day 0 calls completed",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Day 1 starts the night before.",
      },
      {
        id: "cleared",
        label: "Trainees cleared by Day 2",
        target: 70,
        unit: "%",
        kind: "percent",
        why: "≥70% or the batch is broken.",
      },
      {
        id: "improvement",
        label: "Daily skill score improvement",
        target: 10,
        unit: "%",
        kind: "percent",
        why: "10% better every day. Measurable.",
      },
      {
        id: "sims",
        label: "Simulations / trainee",
        target: 5,
        kind: "count",
        why: "5 sims per sprint. No passive watching.",
      },
      {
        id: "support_speak",
        label: "Support Speak instances",
        target: 0,
        kind: "count",
        why: "Zero. Operators, not help desk.",
      },
      {
        id: "go_no_go",
        label: "Go/No-Go report submitted",
        target: 1,
        kind: "boolean",
        why: "By 7:30 PM. No exceptions.",
      },
      {
        id: "sop_updated",
        label: "SOPs updated (this week's errors)",
        target: 1,
        kind: "boolean",
        why: "Same week they're trained.",
      },
      {
        id: "mock_calls",
        label: "Mock calls per trainee",
        target: 3,
        kind: "count",
        why: "3 mocks min — pen-and-paper score each.",
      },
      {
        id: "agenda_check",
        label: "1:1 agenda checks done",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Every trainee, eye-to-eye, no skipping.",
      },
      {
        id: "scripts_redist",
        label: "Corrected scripts redistributed",
        target: 1,
        kind: "boolean",
        why: "Mistake-of-day → fix → in everyone's hand.",
      },
      {
        id: "module_forms",
        label: "Module forms collected",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "No paperwork = no proof of training.",
      },
      {
        id: "intent_score",
        label: "Avg intent score",
        target: 8,
        kind: "count",
        why: "Below 8/10 means we're training the wrong people.",
      },
    ],
    owners: ["e14"],
  },
  talent_engine: {
    role: "Manager",
    kpis: [
      {
        id: "interviews",
        label: "Interviews completed",
        target: 20,
        kind: "count",
        why: "20+ or the pipeline starves.",
      },
      {
        id: "slots_locked",
        label: "Slots locked (today)",
        target: 30,
        kind: "count",
        why: "30 confirmed before 10:30.",
      },
      {
        id: "junior_hr",
        label: "Junior HR contribution",
        target: 5,
        kind: "count",
        why: "Each junior HR = 5 minimum.",
      },
      {
        id: "wa_response",
        label: "WhatsApp response rate",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Silence kills referrals. Zero unread.",
      },
      {
        id: "reminders",
        label: "Internshala reminders sent",
        target: 30,
        kind: "count",
        why: "No slot unreminded.",
      },
      {
        id: "referrals",
        label: "Referral leads contacted",
        target: 15,
        kind: "count",
        why: "Referrals come pre-vetted. Gold.",
      },
      {
        id: "profiles",
        label: "New profiles sourced",
        target: 50,
        kind: "count",
        why: "Pipeline must be heavier at 4 PM than 10:30.",
      },
      {
        id: "tomorrow_locked",
        label: "Tomorrow's pipeline locked",
        target: 30,
        kind: "count",
        why: "By 5:30 PM. No day starts unloaded.",
      },
      {
        id: "intent_q_asked",
        label: "Intent questions asked / interview",
        target: 3,
        kind: "count",
        why: "3 minimum. Otherwise we hire need, not want.",
      },
      {
        id: "ten_min_close",
        label: "Decisions sent within 10 min",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Yes/No/On-Hold while the call is warm.",
      },
      {
        id: "ghost_rate",
        label: "Candidate ghost rate",
        target: 10,
        unit: "%",
        kind: "percent",
        why: "Above 10% = our reminders are weak.",
      },
      {
        id: "junior_audit",
        label: "Junior HR logs audited",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Counts, quality, post-WhatsApps verified daily.",
      },
      {
        id: "jiya_briefed",
        label: "Jiya briefed for tomorrow",
        target: 1,
        kind: "boolean",
        why: "She can't train someone she doesn't know is coming.",
      },
    ],
    owners: ["e15", "e11"],
  },
  pod_command: {
    role: "Floor Lead",
    kpis: [
      {
        id: "pod_conn",
        label: "Pod avg connections / person",
        target: 70,
        kind: "count",
        why: "Hub baseline. Below 70 = pipeline starves.",
      },
      {
        id: "tours_booked",
        label: "Tours booked from pod",
        target: 16,
        kind: "count",
        why: "16 booked → 10 done at 60% show-up.",
      },
      {
        id: "morning_huddle",
        label: "Morning huddle on time",
        target: 1,
        kind: "boolean",
        why: "10:35 sharp. Targets spoken aloud, by name.",
      },
      {
        id: "live_listen",
        label: "Live calls listened-in",
        target: 6,
        kind: "count",
        why: "Listen, intervene, score. Not from your desk only.",
      },
      {
        id: "ride_alongs",
        label: "Field ride-alongs",
        target: 2,
        kind: "count",
        why: "2 site visits with Operators today.",
      },
      {
        id: "crm_clean",
        label: "Pod CRM ghost-lead = 0",
        target: 1,
        kind: "boolean",
        why: "Every lead has a next-step task by 5 PM.",
      },
      {
        id: "one_on_ones",
        label: "1:1s with C-players",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Every C-player gets a written plan today.",
      },
      {
        id: "kudos",
        label: "Kudos given (public)",
        target: 3,
        kind: "count",
        why: "3 named callouts. Energy is a job.",
      },
      {
        id: "blockers_closed",
        label: "Blockers closed today",
        target: 5,
        kind: "count",
        why: "If Operators escalate it, you close it.",
      },
      {
        id: "eod_signed",
        label: "Pod EOD report signed",
        target: 1,
        kind: "boolean",
        why: "Numbers + 1 hard call + 1 fix for tomorrow.",
      },
      {
        id: "owner_calls",
        label: "Property-owner check-ins",
        target: 3,
        kind: "count",
        why: "Inventory health = booking health.",
      },
    ],
    owners: ["e2"],
  },
  tour_conductor: {
    role: "Operator",
    kpis: [
      {
        id: "tours_done",
        label: "Tours conducted",
        target: 6,
        kind: "count",
        why: "Six is the floor. Below six, no claim on output.",
      },
      {
        id: "closings",
        label: "Closings made (after 6)",
        target: 2,
        kind: "count",
        why: "2 minimum. Six tours and zero = the ask was missed.",
      },
      {
        id: "ask_made",
        label: "Explicit ask made / tour",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Every tour ends with a closing question. No exceptions.",
      },
      {
        id: "showup",
        label: "Tour show-up rate today",
        target: 60,
        unit: "%",
        kind: "percent",
        why: "Below 60% = your confirmation calls were soft.",
      },
      {
        id: "confirm_calls",
        label: "Confirmation calls made",
        target: 10,
        kind: "count",
        why: "Confirm 90 min before — every booking, every time.",
      },
      {
        id: "objections_logged",
        label: "Objections logged with quote",
        target: 6,
        kind: "count",
        why: "Real words, real timestamp. Coaching gold.",
      },
      {
        id: "tomorrow_locked",
        label: "Tomorrow's morning tours locked",
        target: 4,
        kind: "count",
        why: "Re-confirmed today, before you leave.",
      },
      {
        id: "site_clean",
        label: "Site presentation OK",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "If the room isn't show-ready, you don't tour it.",
      },
      {
        id: "owner_intro",
        label: "Owner intros done",
        target: 2,
        kind: "count",
        why: "Trust built where the deal happens.",
      },
      {
        id: "deposit_collected",
        label: "Deposits/holds collected",
        target: 1,
        kind: "count",
        why: "Money on the table or it isn't a close.",
      },
      {
        id: "no_show_root",
        label: "No-show root causes named",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Every no-show has a reason. Logged, not guessed.",
      },
    ],
    owners: ["e6"],
  },
  lead_router: {
    role: "Operator",
    kpis: [
      {
        id: "first_touch",
        label: "Avg first-touch time (min)",
        target: 3,
        kind: "count",
        why: "3 min or it goes cold.",
      },
      {
        id: "unassigned",
        label: "Unassigned queue size",
        target: 0,
        kind: "count",
        why: "Every lead has an owner inside 5 min.",
      },
      {
        id: "load_balance",
        label: "Operator load delta",
        target: 5,
        kind: "count",
        why: "No Operator >5 leads ahead of another.",
      },
      {
        id: "dup_merged",
        label: "Duplicates merged",
        target: 10,
        kind: "count",
        why: "Duplicate leads = duplicate calls = lost trust.",
      },
      {
        id: "stale_recycled",
        label: "Stale leads recycled (>72h)",
        target: 15,
        kind: "count",
        why: "Yesterday's silence is today's pipeline.",
      },
      {
        id: "source_health",
        label: "Source health checks",
        target: 6,
        kind: "count",
        why: "Every channel pulse-checked twice/day.",
      },
      {
        id: "spam_blocked",
        label: "Spam/junk leads blocked",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Don't pollute the floor's funnel.",
      },
      {
        id: "tour_handoff",
        label: "Tour handoffs to TCM",
        target: 10,
        kind: "count",
        why: "Clean handoff w/ note + intent score.",
      },
      {
        id: "intent_tag",
        label: "Intent-tagged leads",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Hot/Warm/Cold tagged before assignment.",
      },
      {
        id: "wa_response",
        label: "WhatsApp first-reply <2 min",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Speed kills competitors.",
      },
      {
        id: "queue_zero",
        label: "Queue zero by 7 PM",
        target: 1,
        kind: "boolean",
        why: "End the day with a clean board.",
      },
    ],
    owners: ["e4"],
  },
  people_pulse: {
    role: "HR",
    kpis: [
      {
        id: "att_locked",
        label: "Attendance locked by 10:35",
        target: 1,
        kind: "boolean",
        why: "After 10:35 it's a story, not a fact.",
      },
      {
        id: "late_called",
        label: "Late arrivals called",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Every late mark gets a human call within 15 min.",
      },
      {
        id: "leave_decided",
        label: "Leave requests decided",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "No 'pending' carries past 6 PM.",
      },
      {
        id: "pulse_1on1",
        label: "Pulse 1:1s done",
        target: 4,
        kind: "count",
        why: "4 quiet conversations a day. Catch fires early.",
      },
      {
        id: "birthdays",
        label: "Birthdays/anniversaries acknowledged",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "If we miss it, we're not a team.",
      },
      {
        id: "payroll_exc",
        label: "Payroll exceptions cleared",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Trust pays compounding interest.",
      },
      {
        id: "policy_q",
        label: "Policy questions answered",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "<24h SLA. Always.",
      },
      {
        id: "exit_done",
        label: "Exit interviews on time",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Honest exit = better hires next month.",
      },
      {
        id: "onboarding_kit",
        label: "Onboarding kits ready (D-1)",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Day-1 chaos = month-1 attrition.",
      },
      {
        id: "wellness_check",
        label: "C-player wellness checks",
        target: 2,
        kind: "count",
        why: "C is a signal. Sometimes it's burnout, not skill.",
      },
      {
        id: "compliance",
        label: "Compliance audit clean",
        target: 1,
        kind: "boolean",
        why: "PF, ESI, statutory — no skipped weeks.",
      },
    ],
    owners: ["e8"],
  },
  operator_day: {
    role: "Operator",
    kpis: [
      {
        id: "calls",
        label: "Calls dialed",
        target: 100,
        kind: "count",
        why: "Dial volume = surface area. No volume, no luck.",
      },
      {
        id: "conn",
        label: "Connections (>30s)",
        target: 70,
        kind: "count",
        why: "Pod baseline. Below 70 = below standard.",
      },
      {
        id: "tours_booked",
        label: "Tours booked today",
        target: 4,
        kind: "count",
        why: "Personal floor. 4 booked → 2-3 done.",
      },
      {
        id: "closures",
        label: "Closures",
        target: 1,
        kind: "count",
        why: "1 a day adds up to a great month.",
      },
      {
        id: "wa_replied",
        label: "WhatsApp chats actioned",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "Zero chats older than 24h.",
      },
      {
        id: "next_step",
        label: "Every lead has a next-step task",
        target: 100,
        unit: "%",
        kind: "percent",
        why: "No ghost leads on your CRM.",
      },
      {
        id: "objections_logged",
        label: "Objections logged with quote",
        target: 5,
        kind: "count",
        why: "Real words. Coach uses them tomorrow.",
      },
      {
        id: "ride_along",
        label: "1 site visit / week (today?)",
        target: 1,
        kind: "boolean",
        why: "Field knowledge beats deck knowledge.",
      },
      {
        id: "kudos_given",
        label: "Kudos given to a teammate",
        target: 1,
        kind: "count",
        why: "Energy is contagious. So is silence.",
      },
      {
        id: "training_module",
        label: "Skill module reviewed",
        target: 1,
        kind: "count",
        why: "10 min/day. 60 hrs/year.",
      },
      {
        id: "eod_submitted",
        label: "EOD submitted by 7:30 PM",
        target: 1,
        kind: "boolean",
        why: "EOD checklist completed.",
      },
    ],
    owners: ["e3", "e5", "e7", "e9"],
  },
};

export async function seedKpis() {
  console.log("[KPI Governance Seed] Running seed script...");
  let definitionsCount = 0;
  let targetsCount = 0;

  for (const [pbKey, pbData] of Object.entries(PLAYBOOKS_KPIS)) {
    const categoryName = pbKey
      .split("_")
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(" ");

    for (const kpi of pbData.kpis) {
      // 1. Check or Create Definition
      // Slug format: [playbook_key]_[kpi_id]
      const slug = `${pbKey}_${kpi.id}`;
      let definition = await KpiDefinition.findOne({ slug });

      if (!definition) {
        definition = await KpiDefinition.create({
          id: `kpi-${pbKey}-${kpi.id}`,
          name: kpi.label,
          slug,
          description: kpi.why,
          category: categoryName,
          unit: kpi.unit || "count",
          frequency: "daily",
          aggregationType: kpi.kind === "percent" ? "average" : "sum",
          visibilityScope: "public",
          ownerRole: pbData.role,
          targetType: kpi.id === "support_speak" || kpi.id === "stuck" ? "max" : "min",
          active: true,
          version: 1,
          createdBy: "system",
          updatedBy: "system",
          history: [],
        });
        definitionsCount++;
      }

      // 2. Check or Create Target
      // Org targets for operators, individual targets for managers/leads
      const scopeType = pbData.owners.length > 1 ? "org" : "individual";
      const targetValues = pbData.owners.map((ownerId) => ({
        scopeType: pbData.owners.length > 1 ? "org" : "individual",
        scopeId: pbData.owners.length > 1 ? "org" : ownerId,
        ownerId: ownerId,
      }));

      // Add a fallback org target as well for operators if scopeType is individual
      if (scopeType === "individual") {
        targetValues.push({
          scopeType: "org",
          scopeId: "org",
          ownerId: undefined,
        });
      }

      for (const tv of targetValues) {
        const existingTarget = await KpiTarget.findOne({
          kpiId: definition.id,
          scopeType: tv.scopeType,
          scopeId: tv.scopeId,
        });

        if (!existingTarget) {
          await KpiTarget.create({
            id: `tgt-${pbKey}-${kpi.id}-${tv.scopeId}`,
            kpiId: definition.id,
            scopeType: tv.scopeType,
            scopeId: tv.scopeId,
            targetValue: kpi.target,
            effectiveFrom: "2026-01-01",
            effectiveTo: "2030-12-31",
            ownerId: tv.ownerId,
            notes: `Seeded ${tv.scopeType} target for ${categoryName} - ${kpi.label}`,
            version: 1,
            updatedBy: "system",
            history: [],
          });
          targetsCount++;
        }
      }
    }
  }

  console.log(
    `[KPI Governance Seed] Seed complete. Created ${definitionsCount} new definitions and ${targetsCount} new targets.`,
  );
}
