/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as WarRoomRouteImport } from './routes/war-room'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as RecruitingRouteImport } from './routes/recruiting'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OneOnOnesRouteImport } from './routes/one-on-ones'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as KudosRouteImport } from './routes/kudos'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HrmsRouteImport } from './routes/hrms'
import { Route as ForcePasswordResetRouteImport } from './routes/force-password-reset'
import { Route as FlyRouteImport } from './routes/fly'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminWorkforceRouteImport } from './routes/admin/workforce'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as AdminKpisRouteImport } from './routes/admin/kpis'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const WarRoomRoute = WarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingRoute = RecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OneOnOnesRoute = OneOnOnesRouteImport.update({
  id: '/one-on-ones',
  path: '/one-on-ones',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const KudosRoute = KudosRouteImport.update({
  id: '/kudos',
  path: '/kudos',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsRoute = HrmsRouteImport.update({
  id: '/hrms',
  path: '/hrms',
  getParentRoute: () => rootRouteImport,
} as any)
const ForcePasswordResetRoute = ForcePasswordResetRouteImport.update({
  id: '/force-password-reset',
  path: '/force-password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyRoute = FlyRouteImport.update({
  id: '/fly',
  path: '/fly',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkforceRoute = AdminWorkforceRouteImport.update({
  id: '/admin/workforce',
  path: '/admin/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKpisRoute = AdminKpisRouteImport.update({
  id: '/admin/kpis',
  path: '/admin/kpis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/command': typeof CommandRoute
  '/console': typeof ConsoleRoute
  '/fly': typeof FlyRoute
  '/force-password-reset': typeof ForcePasswordResetRoute
  '/hrms': typeof HrmsRoute
  '/inbox': typeof InboxRoute
  '/kudos': typeof KudosRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/one-on-ones': typeof OneOnOnesRoute
  '/partner': typeof PartnerRoute
  '/people': typeof PeopleRoute
  '/pulse': typeof PulseRoute
  '/recruiting': typeof RecruitingRoute
  '/roster': typeof RosterRoute
  '/score': typeof ScoreRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/war-room': typeof WarRoomRoute
  '/zones': typeof ZonesRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/workforce': typeof AdminWorkforceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/command': typeof CommandRoute
  '/console': typeof ConsoleRoute
  '/fly': typeof FlyRoute
  '/force-password-reset': typeof ForcePasswordResetRoute
  '/hrms': typeof HrmsRoute
  '/inbox': typeof InboxRoute
  '/kudos': typeof KudosRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/one-on-ones': typeof OneOnOnesRoute
  '/partner': typeof PartnerRoute
  '/people': typeof PeopleRoute
  '/pulse': typeof PulseRoute
  '/recruiting': typeof RecruitingRoute
  '/roster': typeof RosterRoute
  '/score': typeof ScoreRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/war-room': typeof WarRoomRoute
  '/zones': typeof ZonesRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/workforce': typeof AdminWorkforceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/command': typeof CommandRoute
  '/console': typeof ConsoleRoute
  '/fly': typeof FlyRoute
  '/force-password-reset': typeof ForcePasswordResetRoute
  '/hrms': typeof HrmsRoute
  '/inbox': typeof InboxRoute
  '/kudos': typeof KudosRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/one-on-ones': typeof OneOnOnesRoute
  '/partner': typeof PartnerRoute
  '/people': typeof PeopleRoute
  '/pulse': typeof PulseRoute
  '/recruiting': typeof RecruitingRoute
  '/roster': typeof RosterRoute
  '/score': typeof ScoreRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/war-room': typeof WarRoomRoute
  '/zones': typeof ZonesRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/workforce': typeof AdminWorkforceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/attendance'
    | '/calendar'
    | '/command'
    | '/console'
    | '/fly'
    | '/force-password-reset'
    | '/hrms'
    | '/inbox'
    | '/kudos'
    | '/leaves'
    | '/login'
    | '/one-on-ones'
    | '/partner'
    | '/people'
    | '/pulse'
    | '/recruiting'
    | '/roster'
    | '/score'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/team'
    | '/war-room'
    | '/zones'
    | '/admin/kpis'
    | '/admin/permissions'
    | '/admin/workforce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/attendance'
    | '/calendar'
    | '/command'
    | '/console'
    | '/fly'
    | '/force-password-reset'
    | '/hrms'
    | '/inbox'
    | '/kudos'
    | '/leaves'
    | '/login'
    | '/one-on-ones'
    | '/partner'
    | '/people'
    | '/pulse'
    | '/recruiting'
    | '/roster'
    | '/score'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/team'
    | '/war-room'
    | '/zones'
    | '/admin/kpis'
    | '/admin/permissions'
    | '/admin/workforce'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/attendance'
    | '/calendar'
    | '/command'
    | '/console'
    | '/fly'
    | '/force-password-reset'
    | '/hrms'
    | '/inbox'
    | '/kudos'
    | '/leaves'
    | '/login'
    | '/one-on-ones'
    | '/partner'
    | '/people'
    | '/pulse'
    | '/recruiting'
    | '/roster'
    | '/score'
    | '/settings'
    | '/signup'
    | '/tasks'
    | '/team'
    | '/war-room'
    | '/zones'
    | '/admin/kpis'
    | '/admin/permissions'
    | '/admin/workforce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AttendanceRoute: typeof AttendanceRoute
  CalendarRoute: typeof CalendarRoute
  CommandRoute: typeof CommandRoute
  ConsoleRoute: typeof ConsoleRoute
  FlyRoute: typeof FlyRoute
  ForcePasswordResetRoute: typeof ForcePasswordResetRoute
  HrmsRoute: typeof HrmsRoute
  InboxRoute: typeof InboxRoute
  KudosRoute: typeof KudosRoute
  LeavesRoute: typeof LeavesRoute
  LoginRoute: typeof LoginRoute
  OneOnOnesRoute: typeof OneOnOnesRoute
  PartnerRoute: typeof PartnerRoute
  PeopleRoute: typeof PeopleRoute
  PulseRoute: typeof PulseRoute
  RecruitingRoute: typeof RecruitingRoute
  RosterRoute: typeof RosterRoute
  ScoreRoute: typeof ScoreRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  WarRoomRoute: typeof WarRoomRoute
  ZonesRoute: typeof ZonesRoute
  AdminKpisRoute: typeof AdminKpisRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminWorkforceRoute: typeof AdminWorkforceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/war-room': {
      id: '/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof WarRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting': {
      id: '/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof RecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one-on-ones': {
      id: '/one-on-ones'
      path: '/one-on-ones'
      fullPath: '/one-on-ones'
      preLoaderRoute: typeof OneOnOnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kudos': {
      id: '/kudos'
      path: '/kudos'
      fullPath: '/kudos'
      preLoaderRoute: typeof KudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms': {
      id: '/hrms'
      path: '/hrms'
      fullPath: '/hrms'
      preLoaderRoute: typeof HrmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/force-password-reset': {
      id: '/force-password-reset'
      path: '/force-password-reset'
      fullPath: '/force-password-reset'
      preLoaderRoute: typeof ForcePasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fly': {
      id: '/fly'
      path: '/fly'
      fullPath: '/fly'
      preLoaderRoute: typeof FlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workforce': {
      id: '/admin/workforce'
      path: '/admin/workforce'
      fullPath: '/admin/workforce'
      preLoaderRoute: typeof AdminWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kpis': {
      id: '/admin/kpis'
      path: '/admin/kpis'
      fullPath: '/admin/kpis'
      preLoaderRoute: typeof AdminKpisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AttendanceRoute: AttendanceRoute,
  CalendarRoute: CalendarRoute,
  CommandRoute: CommandRoute,
  ConsoleRoute: ConsoleRoute,
  FlyRoute: FlyRoute,
  ForcePasswordResetRoute: ForcePasswordResetRoute,
  HrmsRoute: HrmsRoute,
  InboxRoute: InboxRoute,
  KudosRoute: KudosRoute,
  LeavesRoute: LeavesRoute,
  LoginRoute: LoginRoute,
  OneOnOnesRoute: OneOnOnesRoute,
  PartnerRoute: PartnerRoute,
  PeopleRoute: PeopleRoute,
  PulseRoute: PulseRoute,
  RecruitingRoute: RecruitingRoute,
  RosterRoute: RosterRoute,
  ScoreRoute: ScoreRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  WarRoomRoute: WarRoomRoute,
  ZonesRoute: ZonesRoute,
  AdminKpisRoute: AdminKpisRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminWorkforceRoute: AdminWorkforceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
